ALLOWED_CRITERIA = [
    'Accessories',
    'Accuracy',
    'Adjustability',
    'Advanced Features',
    'Application',
    'Apps',
    'Band',
    'Battery Life',
    'Brand',
    'Breathability',
    'Bottom Line',
    'Capacity',
    'Color',
    'Comfort',
    'Compatibility',
    'Compression',
    'Connectivity',
    'Drainage',
    'Drop',
    'Durability',
    'Ease of Use',
    'Effectiveness',
    'Features',
    'Fit',
    'Overall Fit',
    'Flexibility',
    'Grip & Hill',
    'Ground Feel',
    'Heel',
    'Insulation',
    'Materials',
    'Midsole',
    'Model',
    'Motion Control',
    'Outsole',
    'Portability',
    'Potency',
    'Power Source',
    'Product Purity',
    'Protection',
    'Release Date',
    'Responsiveness',
    'Ride',
    'Safety Hazards',
    'Shock Absorption',
    'Side Effects',
    'Size',
    'Sound Quality',
    'Speed',
    'Stability',
    'Style',
    'Support',
    'Terrain',
    'Traction',
    'Update',
    'Upper',
    'Use',
    'UV Protection',
    'Value',
    'Versatility',
    'Visibility',
    'Water Capacity',
    'Water Resistance',
    'Watch Face',
    'Weather Resistance',
    'Weight',
]
